---
name: AnsibleLintOnly
on: workflow_dispatch
 
jobs:
  Setup:
    name: Setup 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Python3  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install ansible lint
        run: pip3 install ansible-lint
      - name: Run Ansible lint
        run: |
           cd molecule
           ansible-lint --version
           ansible-lint -p
           
